version: '3'
services:
  electrum:
    build:
      context: .
      args:
        - VERSION=3.3.8
    ports:
      - 127.0.0.1:7000:7000
    environment:
      ELECTRUM_USER: electrum
      ELECTRUM_PASSWORD: changeme
      ELECTRUM_SEED_PHRASE: changeme
